name: 'peterdataproduct'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbtprof'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"


models:
  peterdataproduct:
    # Config indicated by + and applies to all files under models/staging/
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
